[package]
name = "tracing-subscriber-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.30", features = ["bundled"] }
tracing = "0.1.40"
tracing-log = { version = "0.2.0", optional = true }

[features]
tracing-log = ["dep:tracing-log"]
